FROM debian:11 as builder

RUN apt -y update
RUN apt -y install build-essential libcurl4-openssl-dev libssl-dev

WORKDIR /cmake/

ARG CMAKE_VERSION=3.24.3

ADD https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz .

RUN tar xzf cmake-${CMAKE_VERSION}.tar.gz && \
    cd cmake-${CMAKE_VERSION} && \
    ./bootstrap && \
    make -j $(nproc) && \
    make install

FROM debian:11

COPY --from=builder /usr/ /usr/

CMD [ "bash" ]
