FROM debian:11

RUN apt -y update && \
    apt -y install build-essential vim tar git curl zip unzip pkg-config

RUN git clone https://github.com/microsoft/vcpkg.git && \
    cd /vcpkg && \
    ./bootstrap-vcpkg.sh

WORKDIR /

RUN rm -rf /vcpkg/${VCPKG_VERSION}.tar.gz && /vcpkg/vcpkg install fmt

ENV PATH="$PATH:/vcpkg/"

CMD [ "vcpkg" ]
